config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'tasks/filtered', to: 'tasks#filtered', as: :filtered_tasks
  resources :projects, only: [:show, :index]

  resources :tasks, except: [:new] do
    member do
      post 'toggle'
    end
  end

  get 'home', to: 'test#home'
  get 'frame_test', to: 'test#frame_test'
  root 'test#home'
end

app/models/application_record.rb
# frozen_string_literal: true

# Base class for ActiveRecords.
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true

end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true

  def toggle!
    if completed_at.present?
      update(completed_at: nil)
    else
      update(completed_at: Time.now)
    end
  end

  def completed?
    completed_at.present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Base class for ActionControllers.
require 'flipp_rack_cas/authentication'
class ApplicationController < ActionController::Base

  include FlippRackCas::Authentication

  def unauthorized_error_handler
    server_url = Rails.application.config.rack_cas.server_url
    redirect_to "#{server_url}login?service=#{request.original_url}"
  end
  protect_from_forgery with: :exception

end

app/controllers/ping_controller.rb
# frozen_string_literal: true

# Controller that sends a simple OK message.
class PingController < ApplicationController

  skip_before_action :ensure_logged_in
  def index
    build_commit = ENV['CONTAINER_BUILD_COMMIT'] || ''
    render status: :ok,
           json: {
             commit: build_commit
           }
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    render json: Project.where('name LIKE ?', "%#{params[:q]}%")
  end

  def show
    @project = Project.find_by(id: params[:id])
    @project_name = @project.present? ? @project.name : ''

    if @project.present?
      @tasks = @project.tasks.order(created_at: :desc)
      @task = Task.new
      @total_completed = @tasks.where.not(completed_at: nil).count
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :toggle]

  def filtered
    if params[:q].present?
      # TODO, prevent sql injection here
      @tasks = Task.where("name like '%#{params[:q]}%'")
    else
      @tasks = Task.all
    end
  end

  def toggle
    @task.toggle!
    @project = @task.project
    @total_completed = @project.tasks.where.not(completed_at: nil).count
  end

  def show
    render '_task', locals: { task: @task }
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to project_path(@task.project)
    else
      @tasks = Task.all.order(created_at: :desc)
      # GOTCHA! If you're using Turbo this way you need to 
      # add the status 442 otherwise you'll get a console error in the browser with:
      # Error: Form responses must redirect to another location
      # https://github.com/hotwired/turbo-rails/issues/12#issuecomment-754629885
      render :index, status: 442
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    project = @task.project
    @task.destroy
    redirect_to project_path(project)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task ||= Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :project_id)
    end
end

app/controllers/test_controller.rb
# frozen_string_literal: true

# Sample controller.
class TestController < ApplicationController

  def home
  end

  def frame_test
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Base helper for all views.
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_paginate.html.erb
<% if paginate && paginate.any? %>
  <% param_name = 'page' unless local_assigns[:param_name].present? %>
  <br style="clear:both;"/><br/>
  <div class="pagination"><br/>
    <% if defined?(name) && !name.blank? %>
      <%= page_entries_info paginate, :model => name %>
    <% else %>
      <%= page_entries_info paginate %>
    <% end %>
    <span class="paginate-pages">
    <%= will_paginate paginate,
                      :container => false,
                      :param_name => param_name %>
    </span>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Turbo Stimulus Example Project - <%= yield(:title) if content_for?(:title) %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= favicon_link_tag %>
      <%= javascript_pack_tag 'application' %>
      <%= stylesheet_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://f.wishabi.net/assets/flipp/stylesheets/main_layout.css">
  </head>

  <body id="main_interface">
    <div id="utility-bar">
      <div class="app-display">
        <div>
          <img id="flipp-logo" src="https://f.wishabi.net/assets/flipp/images/logo_white.png" alt="Logo white">
          <div id="app-display-divider"></div>
          <div id="app-name">
            <a href="#">Turbo Stimulus Example Project</a>
          </div>
        </div>
      </div>
    </div>

    <div id="menu-layout">
      <div id="main-content" data-controller="root">
        <% if content_for?(:title) %>
          <h1><%= yield(:title) %>
          <% if content_for?(:description) %>
            <small><%= yield(:description) %></small>
          <% end %>
          </h1>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/projects/show.html.erb
<h1>Search Project</h1>

<div class="ui grid">
  <div
    class="ui scrolling local search five wide column"
    data-controller="project-search"
    data-project-search-fetch-url-value="/projects?q={query}"
    data-project-search-visit-url-value="/projects">
    <div class="ui icon input">
      <input class="prompt" type="text" placeholder="Search Merchant..." value="<%= @project_name %>">
      <i class="search icon"></i>
    </div>
    <div class="results"></div>
  </div>

  <% if @project.present? %>
    <div class="five wide column">
      <h2><%= @project.name %></h2>
    </div>

    <div class="five wide column">
      <h2>
        Total Tasks Completed:
        <%= render partial: 'tasks/total_completed', locals: { 
          total_completed: @total_completed 
        }%>
      </h3>
    </div>
  <% end %>
</div>


<% if @project.present? %>

  <%= render partial: 'tasks/tasks', locals: 
    {
      project: @project,
      task: @task,
      total_completed: @total_completed
    }
  %>
<% end %>

app/views/tasks/_delete_modal.html.erb
<div 
  class="ui tiny modal" data-controller="delete-modal"
  id="delete-modal">
  <i class="close icon"></i>
  <div class="content modal-content">
    <i class="exclamation circle icon modal-icon" style="color: #FFD454"></i>
    <h3 class="modal-header">Are you sure you want to delete this task?</h3>
    <button data-action="click->delete-modal#onDeleteTaskCancel" class="cancel-button"> Cancel </button>
    <a href="#"
       id="delete-link"
       data-method="delete"
       class='delete-link'>Delete</a>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, html: { class: "ui form" }) do |form| %>
  <%= form.hidden_field :project_id, value: project&.id, id: 'form-project-id-input' %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="two fields">
    <div class="field">
      <div class="ui input">
        <%= form.text_field :name, placeholder: 'Enter Task' %>
      </div>
    </div>
    <div class="field">
      <div class="actions">
        <%= form.submit "Create", class: "save-button"%>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_horizontal_form.html.erb
<%= form_with(model: task, html: { class: "ui form" }) do |form| %>
  <div class="two fields">
    <div class="field">
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.submit 'Update', class: "save-button" %>
      <%= link_to "Cancel", task_path(task), class: "cancel-button" %>
    </div>
  </div>
<% end %>

app/views/tasks/_recently_toggled.html.erb
<div class="ui grid">
  <div class="one wide column">
    <% icon_class = task.completed? ? "check" : "exclamation" %>
    <i class="circle icon <%= icon_class %> completed-icon"></i>
  </div>

  <div class="seven wide column">
    <% status = task.completed? ? "completed" : "uncompleted" %>
    Task <%= task.name %> was recently <%= status %>
  </div>

  <% if task.completed? %>
    <div class="seven wide column">
      Completed at <%= task.completed_at.strftime("%B %d, %Y") %>
    </div>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag dom_id(task) do %>
  <div class="ui grid" data-controller="task" data-task-task-id-value="<%= task.id %>" id="task-<%= task.id %>">
    <div class="four wide column">
      <% task_name_class = task.completed? ? 'crossed' : '' %>
      <span class="task-name <%= task_name_class %>"> 
        <%= task.name %>
      </span>
    </div>

    <div class="four wide column text-align-right">
      <!-- LINE TO EDIT will be processed through turbo frames -->
      <%= link_to 'Edit', edit_task_path(task) %>
    </div>

    <div class="four wide column text-align-right">
      <!-- This toggle related thingys should be in a decorator -->
      <% action = task.completed? ? "Uncomplete" : "Complete" %>
      <%= link_to action, toggle_task_path(task), method: :post %>
    </div>

    <div class="four wide column text-align-right">
      <a href="#" data-task-target="deleteLink" data-action="click->task#onShowDeleteConfirmation">Delete</a>
    </div>
  </div>
<% end %>

app/views/tasks/_task_list.html.erb
<div id="task-list">
  <% @tasks.each do |task| %>
    <%= render partial: 'tasks/task', locals: { task: task } %>
  <% end %>
</div>

app/views/tasks/_task_name.html.erb
<span id="task-name-<%= task.id %>" class="task-name <%= task.completed? ? 'crossed' : ''  %>"> 
  <%= task.name %>
</span>

app/views/tasks/_tasks.html.erb
<div class="ui grid">
  <div class="four wide column">
    <h1>Create a New task</h1>

    <%= render 'tasks/form', task: @task, project: project %>
  </div>

  <div class="eight wide column">
    <h1>Tasks</h1>
    <div class="ui input focus task-filter" data-controller='filter' >
      <input type="text" placeholder="Filter by Name" data-action="keyup->filter#onFilterResults" data-filter-target="filterInput" value="">
    </div>

    <!-- 
      GOTCHA!
      Turbo frames do no play out well with table rows. If you try to wrap the 
      <tr></tr> elements with frames (or anything really) the wrappers will get 
      hoisted to outside the table. 
      https://discuss.hotwired.dev/t/how-to-wrap-a-table-row-with-a-turbo-frame/1717/3

      This is relevant for us at Flipp cuz fomantic UI tables https://fomantic-ui.com/collections/table.html use native html table tags. So if you need this setup you'll
      have to roll out your div base table like I'm showing before.
    -->
    <%= render partial: 'tasks/task_list', locals: { tasks: @tasks } %>
  </div>

  <div class="four wide column">
    <h1>Recently Toggled</h1>
    <div id="recently-toggled">
    </div>
  </div>
</div>
<%= render partial: 'tasks/delete_modal' %>

app/views/tasks/_total_completed.html.erb
<span id="total-completed">
  <%= total_completed %>
</span>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.prepend "project-container" do %>
  <%= render partial: "project", locals: { project: @project } %>
<% end %>

app/views/tasks/edit.html.erb
<!--
  Rules:
  - Only the first instance of the response frame will be matched against the corresponding
  browser frame
  - Only the content inside the (browser) frame that initiated the request will be replaced
  => So there's no point in having multiple frames with the same id. You want to be specific 
  about what you want to swap.

  - Nested frames on either side (server response or browser) have not effect on this either.
  => Only the immediate parent frame gets the replaced by the response matching frame.

  - This works for both links and forms submissions

  All these rules are summarized in the first paragraph of https://turbo.hotwired.dev/handbook/frames
-->

<%= turbo_frame_tag dom_id(@task) do %>
  <%= render 'horizontal_form', task: @task %>
<% end %>

app/views/tasks/filtered.turbo_stream.erb
<%= turbo_stream.replace "task-list" do %>
  <%= render partial: "task_list", locals: { tasks: @tasks } %>
<% end %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/toggle.turbo_stream.erb
<%= turbo_stream.append "recently-toggled" do %>
  <%= render partial: "recently_toggled", locals: { task: @task } %>
<% end %>

<%= turbo_stream.replace "total-completed" do %>
  <%= render partial: "total_completed", locals: { total_completed: @total_completed } %>
<% end %>

<%= turbo_stream.replace dom_id(@task) do %>
  <%= render partial: "task", locals: { task: @task } %>
<% end %>
  